server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:flashsale_users}
    username: ${DB_USER:flashsale}
    password: ${DB_PASSWORD:flashsale_dev_pw}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: itBhae1s85oC/xM3OZyNNhdZrpSyVTRXAhICQnMsIDc=
  expiration-ms: 900000   # 15 minutes, in milliseconds